Add code to ci.yml for running examples

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,13 +53,6 @@ jobs:
     # needs: [ test ]  # uncomment to require passing tests
     runs-on: ubuntu-22.04
 
-    # A local registry helps us reuse the built image between steps
-    services:
-      registry:
-        image: registry:2
-        ports:
-          - 5000:5000
-
     steps:
       - name: Get git tag
         id: git_info
@@ -100,6 +93,50 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-buildx-
 
+        # Here, we want to do the docker build twice:
+        # The first build pushes to our local registry for testing.
+        # The second build pushes to Docker Hub and ghcr.io 
+      - name: Build (local only)
+        uses: docker/build-push-action@v3
+        id: docker_build
+        with:
+          context: .
+          file: ./Dockerfile
+          tags: localhost/${{ steps.determine.outputs.dock_image }}
+          load: true
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache
+      # If you have a directory called examples/incoming/ and examples/outgoing/, then
+      # run your ChRIS plugin with no parameters, and asser that it creates all the files
+      # which are expected. File contents are not compared.
+      - name: Run examples
+        id: run_examples
+        run: |
+          if ! [ -d 'examples/incoming/' ] || ! [ -d 'examples/outgoing/' ]; then
+            echo "No examples."
+            exit 0
+          fi
+        
+          dock_image=localhost/${{ steps.determine.outputs.dock_image }}
+          output_dir=$(mktemp -d)
+          cmd=$(docker image inspect -f '{{ (index .Config.Cmd 0) }}' $dock_image)
+          docker run --rm -u "$(id -u):$(id -g)" \
+            -v "$PWD/examples/incoming:/incoming:ro" \
+            -v "$output_dir:/outgoing:rw" \
+            $dock_image $cmd /incoming /outgoing
+          
+          for expected_file in $(find examples/outgoing -type f); do
+            fname="${expected_file##*/}"
+            out_path="$output_dir/$fname"
+            printf "Checking output %s exists..." "$out_path"
+            if [ -f "$out_path" ]; then
+              echo "ok"
+            else
+              echo "not found"
+              exit 1
+            fi
+          done
+
       - name: Login to DockerHub
         id: dockerhub_login
         uses: docker/login-action@v2
@@ -113,24 +150,6 @@ jobs:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
-
-        # Here, we want to do the docker build twice:
-        # The first build pushes to our local registry for testing.
-        # The second build pushes to Docker Hub and ghcr.io 
-      - name: Build (local only)
-        uses: docker/build-push-action@v3
-        id: docker_build
-        with:
-          context: .
-          file: ./Dockerfile
-          tags: |
-            localhost:5000/${{ steps.determine.outputs.dock_image }}
-            docker.io/${{ steps.determine.outputs.dock_image }}
-            ghcr.io/${{ steps.determine.outputs.dock_image }}
-          platforms: linux/amd64
-          push: true
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
       - name: Build and push
         uses: docker/build-push-action@v3
         if: github.event_name == 'push' || github.event_name == 'release'
@@ -138,7 +157,6 @@ jobs:
           context: .
           file: ./Dockerfile
           tags: |
-            localhost:5000/${{ steps.determine.outputs.dock_image }}
             docker.io/${{ steps.determine.outputs.dock_image }}
             ghcr.io/${{ steps.determine.outputs.dock_image }}
           # if non-x86_84 architectures are supported, add them here
@@ -152,7 +170,7 @@ jobs:
         run: |
           repo=${{ steps.determine.outputs.repo }}
           dock_image=${{ steps.determine.outputs.dock_image }}
-          docker run --rm localhost:5000/$dock_image chris_plugin_info > /tmp/description.json
+          docker run --rm localhost/$dock_image chris_plugin_info > /tmp/description.json
           jq < /tmp/description.json  # pretty print in log
           echo "title=$(jq -r '.title' < /tmp/description.json)" >> $GITHUB_OUTPUT
 
