Fix tests

diff --git a/.github/workflows/src.yml b/.github/workflows/src.yml
--- a/.github/workflows/src.yml
+++ b/.github/workflows/src.yml
@@ -35,10 +35,11 @@ jobs:
       - name: Run program
         run: |
           source venv/bin/activate
-          commandname --name ghaction /tmp ./outgoing
-          
-          if ! [ -e 'outgoing/ghaction.txt' ]; then
-            echo "::error ::File outgoing/ghaaction.txt was not created."
+          echo 'on-the-metal test is very testy test test' /tmp/data.txt
+          commandname --word 'test' /tmp ./outgoing
+
+          if ! [ -e 'outgoing/ghaction.count.txt' ]; then
+            echo "::error ::File outgoing/ghaction.count.txt was not created."
           fi
 
   integration:
